### ISSUE TITLE
Why complete example is not added here ?

### ISSUE THREAD

**Issue by tusharuit25** [rhoadster91/android-siesta#1]
Is this library also complete ?

**Comment by rhoadster91** [comment]
Hi,

This library is complete, but is not being maintained. I had published it 2 years ago because I used to write the same wrappers over and over again for my apps and using it as an AAR made sense. But following the release of new Android Architecture components, you can achieve the same thing this library does (with better results) using RxJava and the aforementioned arch components. I have still kept the repo as someone might still find it useful for real-life implementations or educational purposes.

If you find it useful, please feel free to use this code. Apologies for the lack of documentation.
